services:
  overleaf:
    restart: always
    image: sharelatex/sharelatex:ext-ce
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    stop_grace_period: 60s
    volumes:
      - /opt/overleaf/data:/var/lib/overleaf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      SANDBOXED_COMPILES: 'true'
      SANDBOXED_COMPILES_HOST_DIR_COMPILES: '/opt/overleaf/data/data/compiles'
      SANDBOXED_COMPILES_HOST_DIR_OUTPUT: '/opt/overleaf/data/data/output'
      DOCKER_RUNNER: 'true'
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
      ALL_TEX_LIVE_DOCKER_IMAGES: 'texlive/texlive:latest'
      TEX_LIVE_DOCKER_IMAGE: 'texlive/texlive:latest'

  mongo:
    restart: always
    image: mongo:6.0
    command: '--replSet overleaf'
    volumes:
      - /opt/overleaf/mongo:/data/db
      - ./bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: always
    image: redis:6.2
    volumes:
      - /opt/overleaf/redis:/data
