services:
  overleaf:
    restart: always
    image: sharelatex/sharelatex:ext-ce
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    stop_grace_period: 60s
    volumes:
      - overleaf-data:/var/lib/overleaf
    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'

  mongo:
    restart: always
    image: mongo:6.0
    command: '--replSet overleaf'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'try { rs.status() } catch (e) { rs.initiate({ _id: "overleaf", members: [{ _id: 0, host: "mongo:27017" }] }) }' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: always
    image: redis:6.2
    volumes:
      - redis-data:/data

volumes:
  overleaf-data:
  mongo-data:
  redis-data:
